public class HelloWorld {
    String greeting = 'Hello world!';
    
    private String goodMorning = 'Good morning';
    private String goodAfternoon = 'Good afternoon';
    private String goodEvening = 'Good evening';
    private String varFromVSCode = 'Var from VS Code';
    
    
    public void printGreeting() {
        System.debug(greeting);
    }

    public void printgoodMorning() {
        System.debug(goodMorning );
    }
    
    public void printgoodAfternoon() {
        System.debug(goodAfternoon );
    }
    
    public void printgoodEvening() {
        System.debug(goodEvening );
    }
    public void printvarFromVSCode(){
        System.debug(varFromVSCode);
    }

}